# Generated by Django 2.2.2 on 2019-06-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlcoder',
            name='url',
            field=models.CharField(default='https://www.google.com', max_length=255),
        ),
    ]
